New log file opened at Sun Nov 08 15:18:25 CET 2015 by 7076@Gabry-PC
Taking next connection to: 49901
New client attempting to connect on port: 49902-49901
  Address = /192.168.1.7:49901
This client on port 49902 has uuid 36b00541-ab1e-4ae3-9638-0b0bbc372084 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-36b00541-ab1e-4ae3-9638-0b0bbc372084
Taking next connection to: 49901
New client attempting to connect on port: 49903-49901
  Address = /192.168.1.7:49901
Handshake exception on socket: 49903
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49901
New client attempting to connect on port: 49904-49901
  Address = /192.168.1.7:49901
This client on port 49904 has uuid c3c38904-aa0e-48e7-86f6-f66f43ceb254 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-36b00541-ab1e-4ae3-9638-0b0bbc372084, activator-c3c38904-aa0e-48e7-86f6-f66f43ceb254
Taking next connection to: 49901
New client attempting to connect on port: 50187-49901
  Address = /192.168.1.7:49901
Handshake exception on socket: 50187
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49901
New client attempting to connect on port: 50188-49901
  Address = /192.168.1.7:49901
This client on port 50188 has uuid 7a32d857-91aa-469b-8405-36937dbfd674 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-c3c38904-aa0e-48e7-86f6-f66f43ceb254, play-fork-run-7a32d857-91aa-469b-8405-36937dbfd674
Taking next connection to: 49901
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49901
